### ISSUE TITLE
HRIS GroupTypeEnum missing DIVISION

### ISSUE THREAD

**Issue by williamliu52** [merge-api/merge-java-client#63]

**Comment by esfomeado** [comment]
Merge.dev doesn't really care about the state of their SDK so you will wait a while to even get a response from them let alone fix this issue.

**Comment by rmkonnur** [comment]
Hi @williamliu52 - Thank you for raising this issue. As seen in our [Merge Docs](https://docs.merge.dev/hris/groups/), the `type` field does not support the `DIVISION` value officially. However, as with all of our enums, we allow enum values that cannot be well represented by our predefined set of enums to be "passed through" or returned as strings instead of the Enum type. This is handled in `GroupType.java` file (https://github.com/merge-api/merge-java-client/blob/5a7ecb7fd0552a7dc3ba30199e5a924948daedd2/src/main/java/com/merge/api/resources/hris/types/GroupType.java#L32-L39). 

For further questions on our API, feel free to reach out to our Customer Support team via the Merge Dashboard.
